name: Main

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
          validate-wrappers: true
      - run: ./gradlew build

  publish-snapshot:
    needs: build
    runs-on: ubuntu-latest
    if: github.repository == 'Goooler/gradle-legacy-osgi-plugin' && github.ref == 'refs/heads/trunk'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
      # Disable CC due to https://github.com/gradle/gradle/issues/22779
      - run: ./gradlew publish --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
